settings:
  logOnFail: slack

install:
- [ pip install ruff bandit pymarkdownlnt ]

tests:
  assertReturnCode: 0
  ruff:
  - [ ruff check satori_help/ ]
  bandit:
  - [ bandit -r satori_help/ ]
  mdl:
  - [ pymarkdown scan satori_help/docs/ ]
